# Generated by Django 4.2.7 on 2025-11-22 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "category",
                    models.CharField(max_length=100, verbose_name="Категория"),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("white_box", "White Box"),
                            ("finishing", "Finishing"),
                            ("furniture", "Furniture"),
                        ],
                        default="white_box",
                        max_length=50,
                        verbose_name="Этап ремонта",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Цена",
                    ),
                ),
                (
                    "attributes",
                    models.JSONField(blank=True, default=dict, verbose_name="Атрибуты"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("complementary", "Дополняющий"),
                            ("alternative", "Альтернативный"),
                            ("frequently_bought", "Часто покупают вместе"),
                        ],
                        max_length=50,
                        verbose_name="Тип связи",
                    ),
                ),
                ("strength", models.FloatField(default=1.0, verbose_name="Сила связи")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "source_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_relationships",
                        to="products.product",
                        verbose_name="Исходный товар",
                    ),
                ),
                (
                    "target_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_relationships",
                        to="products.product",
                        verbose_name="Целевой товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Связь товаров",
                "verbose_name_plural": "Связи товаров",
                "unique_together": {
                    ("source_product", "target_product", "relationship_type")
                },
            },
        ),
    ]
